from flask import Flask, jsonify, request
from flask_sqlalchemy import SQLAlchemy
import datetime
import os
from config import URI 


app = Flask(__name__)

nba = []

app.config["SQLALCHEMY_DATABASE_URI"] = URI


db = SQLAlchemy(app)

# class season_atl(db.Model):
#     season_id = db.Column(db.Float)
#     team_id= db.Column(db.Float)
#     team_abbreviation = db.Column(db.String(10)) 
#     team_name = db.Column(db.String(30)) 
#     game_id = db.Column(db.Integer, primary_key=True) 
#     game_date = db.Column(db.Date) 
#     matchup = db.Column(db.String(30)) 
#     wl = db.Column(db.String(10)) 
#     min = db.Column(db.Float) 
#     pts = db.Column(db.Float) 
#     fgm = db.Column(db.Float) 
#     fga = db.Column(db.Float)
#     fg_pct = db.Column(db.Float) 
#     fg3m = db.Column(db.Float) 
#     fg3a = db.Column(db.Float)
#     fg3_pct = db.Column(db.Float)
#     ftm = db.Column(db.Float)
#     fta = db.Column(db.Float) 
#     ft_pct = db.Column(db.Float) 
#     oreb = db.Column(db.Float)
#     dreb = db.Column(db.Float) 
#     reb = db.Column(db.Float) 
#     ast = db.Column(db.Float) 
#     stl = db.Column(db.Float) 
#     blk = db.Column(db.Float)
#     tov = db.Column(db.Float)
#     pf = db.Column(db.Float)
#     plus_minus = db.Column(db.Float)
#     is_win = db.Column(db.Float)
#     is_loss = db.Column(db.Float)
#     home_away = db.Column(db.String(10))
#     opponent = db.Column(db.String(10))

# class season_bos(db.Model):
#     season_id = db.Column(db.Float)
#     team_id= db.Column(db.Float)
#     team_abbreviation = db.Column(db.String(10)) 
#     team_name = db.Column(db.String(30)) 
#     game_id = db.Column(db.Integer, primary_key=True) 
#     game_date = db.Column(db.Date) 
#     matchup = db.Column(db.String(30)) 
#     wl = db.Column(db.String(10)) 
#     min = db.Column(db.Float) 
#     pts = db.Column(db.Float) 
#     fgm = db.Column(db.Float) 
#     fga = db.Column(db.Float)
#     fg_pct = db.Column(db.Float) 
#     fg3m = db.Column(db.Float) 
#     fg3a = db.Column(db.Float)
#     fg3_pct = db.Column(db.Float)
#     ftm = db.Column(db.Float)
#     fta = db.Column(db.Float) 
#     ft_pct = db.Column(db.Float) 
#     oreb = db.Column(db.Float)
#     dreb = db.Column(db.Float) 
#     reb = db.Column(db.Float) 
#     ast = db.Column(db.Float) 
#     stl = db.Column(db.Float) 
#     blk = db.Column(db.Float)
#     tov = db.Column(db.Float)
#     pf = db.Column(db.Float)
#     plus_minus = db.Column(db.Float)
#     is_win = db.Column(db.Float)
#     is_loss = db.Column(db.Float)
#     home_away = db.Column(db.String(10))
#     opponent = db.Column(db.String(10))

# class season_bkn(db.Model):
#     season_id = db.Column(db.Float)
#     team_id= db.Column(db.Float)
#     team_abbreviation = db.Column(db.String(10)) 
#     team_name = db.Column(db.String(30)) 
#     game_id = db.Column(db.Integer, primary_key=True) 
#     game_date = db.Column(db.Date) 
#     matchup = db.Column(db.String(30)) 
#     wl = db.Column(db.String(10)) 
#     min = db.Column(db.Float) 
#     pts = db.Column(db.Float) 
#     fgm = db.Column(db.Float) 
#     fga = db.Column(db.Float)
#     fg_pct = db.Column(db.Float) 
#     fg3m = db.Column(db.Float) 
#     fg3a = db.Column(db.Float)
#     fg3_pct = db.Column(db.Float)
#     ftm = db.Column(db.Float)
#     fta = db.Column(db.Float) 
#     ft_pct = db.Column(db.Float) 
#     oreb = db.Column(db.Float)
#     dreb = db.Column(db.Float) 
#     reb = db.Column(db.Float) 
#     ast = db.Column(db.Float) 
#     stl = db.Column(db.Float) 
#     blk = db.Column(db.Float)
#     tov = db.Column(db.Float)
#     pf = db.Column(db.Float)
#     plus_minus = db.Column(db.Float)
#     is_win = db.Column(db.Float)
#     is_loss = db.Column(db.Float)
#     home_away = db.Column(db.String(10))
#     opponent = db.Column(db.String(10))


# class season_chh(db.Model):
#     season_id = db.Column(db.Float)
#     team_id= db.Column(db.Float)
#     team_abbreviation = db.Column(db.String(10)) 
#     team_name = db.Column(db.String(30)) 
#     game_id = db.Column(db.Integer, primary_key=True) 
#     game_date = db.Column(db.Date) 
#     matchup = db.Column(db.String(30)) 
#     wl = db.Column(db.String(10)) 
#     min = db.Column(db.Float) 
#     pts = db.Column(db.Float) 
#     fgm = db.Column(db.Float) 
#     fga = db.Column(db.Float)
#     fg_pct = db.Column(db.Float) 
#     fg3m = db.Column(db.Float) 
#     fg3a = db.Column(db.Float)
#     fg3_pct = db.Column(db.Float)
#     ftm = db.Column(db.Float)
#     fta = db.Column(db.Float) 
#     ft_pct = db.Column(db.Float) 
#     oreb = db.Column(db.Float)
#     dreb = db.Column(db.Float) 
#     reb = db.Column(db.Float) 
#     ast = db.Column(db.Float) 
#     stl = db.Column(db.Float) 
#     blk = db.Column(db.Float)
#     tov = db.Column(db.Float)
#     pf = db.Column(db.Float)
#     plus_minus = db.Column(db.Float)
#     is_win = db.Column(db.Float)
#     is_loss = db.Column(db.Float)
#     home_away = db.Column(db.String(10))
#     opponent = db.Column(db.String(10))

# class season_chi(db.Model):
#     season_id = db.Column(db.Float)
#     team_id= db.Column(db.Float)
#     team_abbreviation = db.Column(db.String(10)) 
#     team_name = db.Column(db.String(30)) 
#     game_id = db.Column(db.Integer, primary_key=True) 
#     game_date = db.Column(db.Date) 
#     matchup = db.Column(db.String(30)) 
#     wl = db.Column(db.String(10)) 
#     min = db.Column(db.Float) 
#     pts = db.Column(db.Float) 
#     fgm = db.Column(db.Float) 
#     fga = db.Column(db.Float)
#     fg_pct = db.Column(db.Float) 
#     fg3m = db.Column(db.Float) 
#     fg3a = db.Column(db.Float)
#     fg3_pct = db.Column(db.Float)
#     ftm = db.Column(db.Float)
#     fta = db.Column(db.Float) 
#     ft_pct = db.Column(db.Float) 
#     oreb = db.Column(db.Float)
#     dreb = db.Column(db.Float) 
#     reb = db.Column(db.Float) 
#     ast = db.Column(db.Float) 
#     stl = db.Column(db.Float) 
#     blk = db.Column(db.Float)
#     tov = db.Column(db.Float)
#     pf = db.Column(db.Float)
#     plus_minus = db.Column(db.Float)
#     is_win = db.Column(db.Float)
#     is_loss = db.Column(db.Float)
#     home_away = db.Column(db.String(10))
#     opponent = db.Column(db.String(10))

# class season_cle(db.Model):
#     season_id = db.Column(db.Float)
#     team_id= db.Column(db.Float)
#     team_abbreviation = db.Column(db.String(10)) 
#     team_name = db.Column(db.String(30)) 
#     game_id = db.Column(db.Integer, primary_key=True) 
#     game_date = db.Column(db.Date) 
#     matchup = db.Column(db.String(30)) 
#     wl = db.Column(db.String(10)) 
#     min = db.Column(db.Float) 
#     pts = db.Column(db.Float) 
#     fgm = db.Column(db.Float) 
#     fga = db.Column(db.Float)
#     fg_pct = db.Column(db.Float) 
#     fg3m = db.Column(db.Float) 
#     fg3a = db.Column(db.Float)
#     fg3_pct = db.Column(db.Float)
#     ftm = db.Column(db.Float)
#     fta = db.Column(db.Float) 
#     ft_pct = db.Column(db.Float) 
#     oreb = db.Column(db.Float)
#     dreb = db.Column(db.Float) 
#     reb = db.Column(db.Float) 
#     ast = db.Column(db.Float) 
#     stl = db.Column(db.Float) 
#     blk = db.Column(db.Float)
#     tov = db.Column(db.Float)
#     pf = db.Column(db.Float)
#     plus_minus = db.Column(db.Float)
#     is_win = db.Column(db.Float)
#     is_loss = db.Column(db.Float)
#     home_away = db.Column(db.String(10))
#     opponent = db.Column(db.String(10))

# class season_dal(db.Model):
#     season_id = db.Column(db.Float)
#     team_id= db.Column(db.Float)
#     team_abbreviation = db.Column(db.String(10)) 
#     team_name = db.Column(db.String(30)) 
#     game_id = db.Column(db.Integer, primary_key=True) 
#     game_date = db.Column(db.Date) 
#     matchup = db.Column(db.String(30)) 
#     wl = db.Column(db.String(10)) 
#     min = db.Column(db.Float) 
#     pts = db.Column(db.Float) 
#     fgm = db.Column(db.Float) 
#     fga = db.Column(db.Float)
#     fg_pct = db.Column(db.Float) 
#     fg3m = db.Column(db.Float) 
#     fg3a = db.Column(db.Float)
#     fg3_pct = db.Column(db.Float)
#     ftm = db.Column(db.Float)
#     fta = db.Column(db.Float) 
#     ft_pct = db.Column(db.Float) 
#     oreb = db.Column(db.Float)
#     dreb = db.Column(db.Float) 
#     reb = db.Column(db.Float) 
#     ast = db.Column(db.Float) 
#     stl = db.Column(db.Float) 
#     blk = db.Column(db.Float)
#     tov = db.Column(db.Float)
#     pf = db.Column(db.Float)
#     plus_minus = db.Column(db.Float)
#     is_win = db.Column(db.Float)
#     is_loss = db.Column(db.Float)
#     home_away = db.Column(db.String(10))
#     opponent = db.Column(db.String(10))

# class season_den(db.Model):
#     season_id = db.Column(db.Float)
#     team_id= db.Column(db.Float)
#     team_abbreviation = db.Column(db.String(10)) 
#     team_name = db.Column(db.String(30)) 
#     game_id = db.Column(db.Integer, primary_key=True) 
#     game_date = db.Column(db.Date) 
#     matchup = db.Column(db.String(30)) 
#     wl = db.Column(db.String(10)) 
#     min = db.Column(db.Float) 
#     pts = db.Column(db.Float) 
#     fgm = db.Column(db.Float) 
#     fga = db.Column(db.Float)
#     fg_pct = db.Column(db.Float) 
#     fg3m = db.Column(db.Float) 
#     fg3a = db.Column(db.Float)
#     fg3_pct = db.Column(db.Float)
#     ftm = db.Column(db.Float)
#     fta = db.Column(db.Float) 
#     ft_pct = db.Column(db.Float) 
#     oreb = db.Column(db.Float)
#     dreb = db.Column(db.Float) 
#     reb = db.Column(db.Float) 
#     ast = db.Column(db.Float) 
#     stl = db.Column(db.Float) 
#     blk = db.Column(db.Float)
#     tov = db.Column(db.Float)
#     pf = db.Column(db.Float)
#     plus_minus = db.Column(db.Float)
#     is_win = db.Column(db.Float)
#     is_loss = db.Column(db.Float)
#     home_away = db.Column(db.String(10))
#     opponent = db.Column(db.String(10))


# class season_det(db.Model):
#     season_id = db.Column(db.Float)
#     team_id= db.Column(db.Float)
#     team_abbreviation = db.Column(db.String(10)) 
#     team_name = db.Column(db.String(30)) 
#     game_id = db.Column(db.Integer, primary_key=True) 
#     game_date = db.Column(db.Date) 
#     matchup = db.Column(db.String(30)) 
#     wl = db.Column(db.String(10)) 
#     min = db.Column(db.Float) 
#     pts = db.Column(db.Float) 
#     fgm = db.Column(db.Float) 
#     fga = db.Column(db.Float)
#     fg_pct = db.Column(db.Float) 
#     fg3m = db.Column(db.Float) 
#     fg3a = db.Column(db.Float)
#     fg3_pct = db.Column(db.Float)
#     ftm = db.Column(db.Float)
#     fta = db.Column(db.Float) 
#     ft_pct = db.Column(db.Float) 
#     oreb = db.Column(db.Float)
#     dreb = db.Column(db.Float) 
#     reb = db.Column(db.Float) 
#     ast = db.Column(db.Float) 
#     stl = db.Column(db.Float) 
#     blk = db.Column(db.Float)
#     tov = db.Column(db.Float)
#     pf = db.Column(db.Float)
#     plus_minus = db.Column(db.Float)
#     is_win = db.Column(db.Float)
#     is_loss = db.Column(db.Float)
#     home_away = db.Column(db.String(10))
#     opponent = db.Column(db.String(10))

# class season_gsw(db.Model):
#     season_id = db.Column(db.Float)
#     team_id= db.Column(db.Float)
#     team_abbreviation = db.Column(db.String(10)) 
#     team_name = db.Column(db.String(30)) 
#     game_id = db.Column(db.Integer, primary_key=True) 
#     game_date = db.Column(db.Date) 
#     matchup = db.Column(db.String(30)) 
#     wl = db.Column(db.String(10)) 
#     min = db.Column(db.Float) 
#     pts = db.Column(db.Float) 
#     fgm = db.Column(db.Float) 
#     fga = db.Column(db.Float)
#     fg_pct = db.Column(db.Float) 
#     fg3m = db.Column(db.Float) 
#     fg3a = db.Column(db.Float)
#     fg3_pct = db.Column(db.Float)
#     ftm = db.Column(db.Float)
#     fta = db.Column(db.Float) 
#     ft_pct = db.Column(db.Float) 
#     oreb = db.Column(db.Float)
#     dreb = db.Column(db.Float) 
#     reb = db.Column(db.Float) 
#     ast = db.Column(db.Float) 
#     stl = db.Column(db.Float) 
#     blk = db.Column(db.Float)
#     tov = db.Column(db.Float)
#     pf = db.Column(db.Float)
#     plus_minus = db.Column(db.Float)
#     is_win = db.Column(db.Float)
#     is_loss = db.Column(db.Float)
#     home_away = db.Column(db.String(10))
#     opponent = db.Column(db.String(10))

# class season_hou(db.Model):
#     season_id = db.Column(db.Float)
#     team_id= db.Column(db.Float)
#     team_abbreviation = db.Column(db.String(10)) 
#     team_name = db.Column(db.String(30)) 
#     game_id = db.Column(db.Integer, primary_key=True) 
#     game_date = db.Column(db.Date) 
#     matchup = db.Column(db.String(30)) 
#     wl = db.Column(db.String(10)) 
#     min = db.Column(db.Float) 
#     pts = db.Column(db.Float) 
#     fgm = db.Column(db.Float) 
#     fga = db.Column(db.Float)
#     fg_pct = db.Column(db.Float) 
#     fg3m = db.Column(db.Float) 
#     fg3a = db.Column(db.Float)
#     fg3_pct = db.Column(db.Float)
#     ftm = db.Column(db.Float)
#     fta = db.Column(db.Float) 
#     ft_pct = db.Column(db.Float) 
#     oreb = db.Column(db.Float)
#     dreb = db.Column(db.Float) 
#     reb = db.Column(db.Float) 
#     ast = db.Column(db.Float) 
#     stl = db.Column(db.Float) 
#     blk = db.Column(db.Float)
#     tov = db.Column(db.Float)
#     pf = db.Column(db.Float)
#     plus_minus = db.Column(db.Float)
#     is_win = db.Column(db.Float)
#     is_loss = db.Column(db.Float)
#     home_away = db.Column(db.String(10))
#     opponent = db.Column(db.String(10))

# class season_ind(db.Model):
#     season_id = db.Column(db.Float)
#     team_id= db.Column(db.Float)
#     team_abbreviation = db.Column(db.String(10)) 
#     team_name = db.Column(db.String(30)) 
#     game_id = db.Column(db.Integer, primary_key=True) 
#     game_date = db.Column(db.Date) 
#     matchup = db.Column(db.String(30)) 
#     wl = db.Column(db.String(10)) 
#     min = db.Column(db.Float) 
#     pts = db.Column(db.Float) 
#     fgm = db.Column(db.Float) 
#     fga = db.Column(db.Float)
#     fg_pct = db.Column(db.Float) 
#     fg3m = db.Column(db.Float) 
#     fg3a = db.Column(db.Float)
#     fg3_pct = db.Column(db.Float)
#     ftm = db.Column(db.Float)
#     fta = db.Column(db.Float) 
#     ft_pct = db.Column(db.Float) 
#     oreb = db.Column(db.Float)
#     dreb = db.Column(db.Float) 
#     reb = db.Column(db.Float) 
#     ast = db.Column(db.Float) 
#     stl = db.Column(db.Float) 
#     blk = db.Column(db.Float)
#     tov = db.Column(db.Float)
#     pf = db.Column(db.Float)
#     plus_minus = db.Column(db.Float)
#     is_win = db.Column(db.Float)
#     is_loss = db.Column(db.Float)
#     home_away = db.Column(db.String(10))
#     opponent = db.Column(db.String(10))

# class season_kck_sac(db.Model):
#     season_id = db.Column(db.Float)
#     team_id= db.Column(db.Float)
#     team_abbreviation = db.Column(db.String(10)) 
#     team_name = db.Column(db.String(30)) 
#     game_id = db.Column(db.Integer, primary_key=True) 
#     game_date = db.Column(db.Date) 
#     matchup = db.Column(db.String(30)) 
#     wl = db.Column(db.String(10)) 
#     min = db.Column(db.Float) 
#     pts = db.Column(db.Float) 
#     fgm = db.Column(db.Float) 
#     fga = db.Column(db.Float)
#     fg_pct = db.Column(db.Float) 
#     fg3m = db.Column(db.Float) 
#     fg3a = db.Column(db.Float)
#     fg3_pct = db.Column(db.Float)
#     ftm = db.Column(db.Float)
#     fta = db.Column(db.Float) 
#     ft_pct = db.Column(db.Float) 
#     oreb = db.Column(db.Float)
#     dreb = db.Column(db.Float) 
#     reb = db.Column(db.Float) 
#     ast = db.Column(db.Float) 
#     stl = db.Column(db.Float) 
#     blk = db.Column(db.Float)
#     tov = db.Column(db.Float)
#     pf = db.Column(db.Float)
#     plus_minus = db.Column(db.Float)
#     is_win = db.Column(db.Float)
#     is_loss = db.Column(db.Float)
#     home_away = db.Column(db.String(10))
#     opponent = db.Column(db.String(10))

# class season_lac_sdc(db.Model):
#     season_id = db.Column(db.Float)
#     team_id= db.Column(db.Float)
#     team_abbreviation = db.Column(db.String(10)) 
#     team_name = db.Column(db.String(30)) 
#     game_id = db.Column(db.Integer, primary_key=True) 
#     game_date = db.Column(db.Date) 
#     matchup = db.Column(db.String(30)) 
#     wl = db.Column(db.String(10)) 
#     min = db.Column(db.Float) 
#     pts = db.Column(db.Float) 
#     fgm = db.Column(db.Float) 
#     fga = db.Column(db.Float)
#     fg_pct = db.Column(db.Float) 
#     fg3m = db.Column(db.Float) 
#     fg3a = db.Column(db.Float)
#     fg3_pct = db.Column(db.Float)
#     ftm = db.Column(db.Float)
#     fta = db.Column(db.Float) 
#     ft_pct = db.Column(db.Float) 
#     oreb = db.Column(db.Float)
#     dreb = db.Column(db.Float) 
#     reb = db.Column(db.Float) 
#     ast = db.Column(db.Float) 
#     stl = db.Column(db.Float) 
#     blk = db.Column(db.Float)
#     tov = db.Column(db.Float)
#     pf = db.Column(db.Float)
#     plus_minus = db.Column(db.Float)
#     is_win = db.Column(db.Float)
#     is_loss = db.Column(db.Float)
#     home_away = db.Column(db.String(10))
#     opponent = db.Column(db.String(10))

# class season_lal(db.Model):
#     season_id = db.Column(db.Float)
#     team_id= db.Column(db.Float)
#     team_abbreviation = db.Column(db.String(10)) 
#     team_name = db.Column(db.String(30)) 
#     game_id = db.Column(db.Integer, primary_key=True) 
#     game_date = db.Column(db.Date) 
#     matchup = db.Column(db.String(30)) 
#     wl = db.Column(db.String(10)) 
#     min = db.Column(db.Float) 
#     pts = db.Column(db.Float) 
#     fgm = db.Column(db.Float) 
#     fga = db.Column(db.Float)
#     fg_pct = db.Column(db.Float) 
#     fg3m = db.Column(db.Float) 
#     fg3a = db.Column(db.Float)
#     fg3_pct = db.Column(db.Float)
#     ftm = db.Column(db.Float)
#     fta = db.Column(db.Float) 
#     ft_pct = db.Column(db.Float) 
#     oreb = db.Column(db.Float)
#     dreb = db.Column(db.Float) 
#     reb = db.Column(db.Float) 
#     ast = db.Column(db.Float) 
#     stl = db.Column(db.Float) 
#     blk = db.Column(db.Float)
#     tov = db.Column(db.Float)
#     pf = db.Column(db.Float)
#     plus_minus = db.Column(db.Float)
#     is_win = db.Column(db.Float)
#     is_loss = db.Column(db.Float)
#     home_away = db.Column(db.String(10))
#     opponent = db.Column(db.String(10))

# class season_okc_sea(db.Model):
#     season_id = db.Column(db.Float)
#     team_id= db.Column(db.Float)
#     team_abbreviation = db.Column(db.String(10)) 
#     team_name = db.Column(db.String(30)) 
#     game_id = db.Column(db.Integer, primary_key=True) 
#     game_date = db.Column(db.Date) 
#     matchup = db.Column(db.String(30)) 
#     wl = db.Column(db.String(10)) 
#     min = db.Column(db.Float) 
#     pts = db.Column(db.Float) 
#     fgm = db.Column(db.Float) 
#     fga = db.Column(db.Float)
#     fg_pct = db.Column(db.Float) 
#     fg3m = db.Column(db.Float) 
#     fg3a = db.Column(db.Float)
#     fg3_pct = db.Column(db.Float)
#     ftm = db.Column(db.Float)
#     fta = db.Column(db.Float) 
#     ft_pct = db.Column(db.Float) 
#     oreb = db.Column(db.Float)
#     dreb = db.Column(db.Float) 
#     reb = db.Column(db.Float) 
#     ast = db.Column(db.Float) 
#     stl = db.Column(db.Float) 
#     blk = db.Column(db.Float)
#     tov = db.Column(db.Float)
#     pf = db.Column(db.Float)
#     plus_minus = db.Column(db.Float)
#     is_win = db.Column(db.Float)
#     is_loss = db.Column(db.Float)
#     home_away = db.Column(db.String(10))
#     opponent = db.Column(db.String(10))


# class season_mem_van(db.Model):
#     season_id = db.Column(db.Float)
#     team_id= db.Column(db.Float)
#     team_abbreviation = db.Column(db.String(10)) 
#     team_name = db.Column(db.String(30)) 
#     game_id = db.Column(db.Integer, primary_key=True) 
#     game_date = db.Column(db.Date) 
#     matchup = db.Column(db.String(30)) 
#     wl = db.Column(db.String(10)) 
#     min = db.Column(db.Float) 
#     pts = db.Column(db.Float) 
#     fgm = db.Column(db.Float) 
#     fga = db.Column(db.Float)
#     fg_pct = db.Column(db.Float) 
#     fg3m = db.Column(db.Float) 
#     fg3a = db.Column(db.Float)
#     fg3_pct = db.Column(db.Float)
#     ftm = db.Column(db.Float)
#     fta = db.Column(db.Float) 
#     ft_pct = db.Column(db.Float) 
#     oreb = db.Column(db.Float)
#     dreb = db.Column(db.Float) 
#     reb = db.Column(db.Float) 
#     ast = db.Column(db.Float) 
#     stl = db.Column(db.Float) 
#     blk = db.Column(db.Float)
#     tov = db.Column(db.Float)
#     pf = db.Column(db.Float)
#     plus_minus = db.Column(db.Float)
#     is_win = db.Column(db.Float)
#     is_loss = db.Column(db.Float)
#     home_away = db.Column(db.String(10))
#     opponent = db.Column(db.String(10))


# class season_mia(db.Model):
#     season_id = db.Column(db.Float)
#     team_id= db.Column(db.Float)
#     team_abbreviation = db.Column(db.String(10)) 
#     team_name = db.Column(db.String(30)) 
#     game_id = db.Column(db.Integer, primary_key=True) 
#     game_date = db.Column(db.Date) 
#     matchup = db.Column(db.String(30)) 
#     wl = db.Column(db.String(10)) 
#     min = db.Column(db.Float) 
#     pts = db.Column(db.Float) 
#     fgm = db.Column(db.Float) 
#     fga = db.Column(db.Float)
#     fg_pct = db.Column(db.Float) 
#     fg3m = db.Column(db.Float) 
#     fg3a = db.Column(db.Float)
#     fg3_pct = db.Column(db.Float)
#     ftm = db.Column(db.Float)
#     fta = db.Column(db.Float) 
#     ft_pct = db.Column(db.Float) 
#     oreb = db.Column(db.Float)
#     dreb = db.Column(db.Float) 
#     reb = db.Column(db.Float) 
#     ast = db.Column(db.Float) 
#     stl = db.Column(db.Float) 
#     blk = db.Column(db.Float)
#     tov = db.Column(db.Float)
#     pf = db.Column(db.Float)
#     plus_minus = db.Column(db.Float)
#     is_win = db.Column(db.Float)
#     is_loss = db.Column(db.Float)
#     home_away = db.Column(db.String(10))
#     opponent = db.Column(db.String(10))


# class season_mil(db.Model):
#     season_id = db.Column(db.Float)
#     team_id= db.Column(db.Float)
#     team_abbreviation = db.Column(db.String(10)) 
#     team_name = db.Column(db.String(30)) 
#     game_id = db.Column(db.Integer, primary_key=True) 
#     game_date = db.Column(db.Date) 
#     matchup = db.Column(db.String(30)) 
#     wl = db.Column(db.String(10)) 
#     min = db.Column(db.Float) 
#     pts = db.Column(db.Float) 
#     fgm = db.Column(db.Float) 
#     fga = db.Column(db.Float)
#     fg_pct = db.Column(db.Float) 
#     fg3m = db.Column(db.Float) 
#     fg3a = db.Column(db.Float)
#     fg3_pct = db.Column(db.Float)
#     ftm = db.Column(db.Float)
#     fta = db.Column(db.Float) 
#     ft_pct = db.Column(db.Float) 
#     oreb = db.Column(db.Float)
#     dreb = db.Column(db.Float) 
#     reb = db.Column(db.Float) 
#     ast = db.Column(db.Float) 
#     stl = db.Column(db.Float) 
#     blk = db.Column(db.Float)
#     tov = db.Column(db.Float)
#     pf = db.Column(db.Float)
#     plus_minus = db.Column(db.Float)
#     is_win = db.Column(db.Float)
#     is_loss = db.Column(db.Float)
#     home_away = db.Column(db.String(10))
#     opponent = db.Column(db.String(10))


# class season_min(db.Model):
#     season_id = db.Column(db.Float)
#     team_id= db.Column(db.Float)
#     team_abbreviation = db.Column(db.String(10)) 
#     team_name = db.Column(db.String(30)) 
#     game_id = db.Column(db.Integer, primary_key=True) 
#     game_date = db.Column(db.Date) 
#     matchup = db.Column(db.String(30)) 
#     wl = db.Column(db.String(10)) 
#     min = db.Column(db.Float) 
#     pts = db.Column(db.Float) 
#     fgm = db.Column(db.Float) 
#     fga = db.Column(db.Float)
#     fg_pct = db.Column(db.Float) 
#     fg3m = db.Column(db.Float) 
#     fg3a = db.Column(db.Float)
#     fg3_pct = db.Column(db.Float)
#     ftm = db.Column(db.Float)
#     fta = db.Column(db.Float) 
#     ft_pct = db.Column(db.Float) 
#     oreb = db.Column(db.Float)
#     dreb = db.Column(db.Float) 
#     reb = db.Column(db.Float) 
#     ast = db.Column(db.Float) 
#     stl = db.Column(db.Float) 
#     blk = db.Column(db.Float)
#     tov = db.Column(db.Float)
#     pf = db.Column(db.Float)
#     plus_minus = db.Column(db.Float)
#     is_win = db.Column(db.Float)
#     is_loss = db.Column(db.Float)
#     home_away = db.Column(db.String(10))
#     opponent = db.Column(db.String(10))


# class season_njn(db.Model):
#     season_id = db.Column(db.Float)
#     team_id= db.Column(db.Float)
#     team_abbreviation = db.Column(db.String(10)) 
#     team_name = db.Column(db.String(30)) 
#     game_id = db.Column(db.Integer, primary_key=True) 
#     game_date = db.Column(db.Date) 
#     matchup = db.Column(db.String(30)) 
#     wl = db.Column(db.String(10)) 
#     min = db.Column(db.Float) 
#     pts = db.Column(db.Float) 
#     fgm = db.Column(db.Float) 
#     fga = db.Column(db.Float)
#     fg_pct = db.Column(db.Float) 
#     fg3m = db.Column(db.Float) 
#     fg3a = db.Column(db.Float)
#     fg3_pct = db.Column(db.Float)
#     ftm = db.Column(db.Float)
#     fta = db.Column(db.Float) 
#     ft_pct = db.Column(db.Float) 
#     oreb = db.Column(db.Float)
#     dreb = db.Column(db.Float) 
#     reb = db.Column(db.Float) 
#     ast = db.Column(db.Float) 
#     stl = db.Column(db.Float) 
#     blk = db.Column(db.Float)
#     tov = db.Column(db.Float)
#     pf = db.Column(db.Float)
#     plus_minus = db.Column(db.Float)
#     is_win = db.Column(db.Float)
#     is_loss = db.Column(db.Float)
#     home_away = db.Column(db.String(10))
#     opponent = db.Column(db.String(10))


# class season_noh_nop_nok(db.Model):
#     season_id = db.Column(db.Float)
#     team_id= db.Column(db.Float)
#     team_abbreviation = db.Column(db.String(10)) 
#     team_name = db.Column(db.String(50)) 
#     game_id = db.Column(db.Integer, primary_key=True) 
#     game_date = db.Column(db.Date) 
#     matchup = db.Column(db.String(50)) 
#     wl = db.Column(db.String(10)) 
#     min = db.Column(db.Float) 
#     pts = db.Column(db.Float) 
#     fgm = db.Column(db.Float) 
#     fga = db.Column(db.Float)
#     fg_pct = db.Column(db.Float) 
#     fg3m = db.Column(db.Float) 
#     fg3a = db.Column(db.Float)
#     fg3_pct = db.Column(db.Float)
#     ftm = db.Column(db.Float)
#     fta = db.Column(db.Float) 
#     ft_pct = db.Column(db.Float) 
#     oreb = db.Column(db.Float)
#     dreb = db.Column(db.Float) 
#     reb = db.Column(db.Float) 
#     ast = db.Column(db.Float) 
#     stl = db.Column(db.Float) 
#     blk = db.Column(db.Float)
#     tov = db.Column(db.Float)
#     pf = db.Column(db.Float)
#     plus_minus = db.Column(db.Float)
#     is_win = db.Column(db.Float)
#     is_loss = db.Column(db.Float)
#     home_away = db.Column(db.String(10))
#     opponent = db.Column(db.String(10))

# class season_nyk(db.Model):
#     season_id = db.Column(db.Float)
#     team_id= db.Column(db.Float)
#     team_abbreviation = db.Column(db.String(10)) 
#     team_name = db.Column(db.String(30)) 
#     game_id = db.Column(db.Integer, primary_key=True) 
#     game_date = db.Column(db.Date) 
#     matchup = db.Column(db.String(30)) 
#     wl = db.Column(db.String(10)) 
#     min = db.Column(db.Float) 
#     pts = db.Column(db.Float) 
#     fgm = db.Column(db.Float) 
#     fga = db.Column(db.Float)
#     fg_pct = db.Column(db.Float) 
#     fg3m = db.Column(db.Float) 
#     fg3a = db.Column(db.Float)
#     fg3_pct = db.Column(db.Float)
#     ftm = db.Column(db.Float)
#     fta = db.Column(db.Float) 
#     ft_pct = db.Column(db.Float) 
#     oreb = db.Column(db.Float)
#     dreb = db.Column(db.Float) 
#     reb = db.Column(db.Float) 
#     ast = db.Column(db.Float) 
#     stl = db.Column(db.Float) 
#     blk = db.Column(db.Float)
#     tov = db.Column(db.Float)
#     pf = db.Column(db.Float)
#     plus_minus = db.Column(db.Float)
#     is_win = db.Column(db.Float)
#     is_loss = db.Column(db.Float)
#     home_away = db.Column(db.String(10))
#     opponent = db.Column(db.String(10))

# class season_orl(db.Model):
#     season_id = db.Column(db.Float)
#     team_id= db.Column(db.Float)
#     team_abbreviation = db.Column(db.String(10)) 
#     team_name = db.Column(db.String(30)) 
#     game_id = db.Column(db.Integer, primary_key=True) 
#     game_date = db.Column(db.Date) 
#     matchup = db.Column(db.String(30)) 
#     wl = db.Column(db.String(10)) 
#     min = db.Column(db.Float) 
#     pts = db.Column(db.Float) 
#     fgm = db.Column(db.Float) 
#     fga = db.Column(db.Float)
#     fg_pct = db.Column(db.Float) 
#     fg3m = db.Column(db.Float) 
#     fg3a = db.Column(db.Float)
#     fg3_pct = db.Column(db.Float)
#     ftm = db.Column(db.Float)
#     fta = db.Column(db.Float) 
#     ft_pct = db.Column(db.Float) 
#     oreb = db.Column(db.Float)
#     dreb = db.Column(db.Float) 
#     reb = db.Column(db.Float) 
#     ast = db.Column(db.Float) 
#     stl = db.Column(db.Float) 
#     blk = db.Column(db.Float)
#     tov = db.Column(db.Float)
#     pf = db.Column(db.Float)
#     plus_minus = db.Column(db.Float)
#     is_win = db.Column(db.Float)
#     is_loss = db.Column(db.Float)
#     home_away = db.Column(db.String(10))
#     opponent = db.Column(db.String(10))

# class season_phi_phl(db.Model):
#     season_id = db.Column(db.Float)
#     team_id= db.Column(db.Float)
#     team_abbreviation = db.Column(db.String(10)) 
#     team_name = db.Column(db.String(30)) 
#     game_id = db.Column(db.Integer, primary_key=True) 
#     game_date = db.Column(db.Date) 
#     matchup = db.Column(db.String(30)) 
#     wl = db.Column(db.String(10)) 
#     min = db.Column(db.Float) 
#     pts = db.Column(db.Float) 
#     fgm = db.Column(db.Float) 
#     fga = db.Column(db.Float)
#     fg_pct = db.Column(db.Float) 
#     fg3m = db.Column(db.Float) 
#     fg3a = db.Column(db.Float)
#     fg3_pct = db.Column(db.Float)
#     ftm = db.Column(db.Float)
#     fta = db.Column(db.Float) 
#     ft_pct = db.Column(db.Float) 
#     oreb = db.Column(db.Float)
#     dreb = db.Column(db.Float) 
#     reb = db.Column(db.Float) 
#     ast = db.Column(db.Float) 
#     stl = db.Column(db.Float) 
#     blk = db.Column(db.Float)
#     tov = db.Column(db.Float)
#     pf = db.Column(db.Float)
#     plus_minus = db.Column(db.Float)
#     is_win = db.Column(db.Float)
#     is_loss = db.Column(db.Float)
#     home_away = db.Column(db.String(10))
#     opponent = db.Column(db.String(10))

# class season_phx(db.Model):
#     season_id = db.Column(db.Float)
#     team_id= db.Column(db.Float)
#     team_abbreviation = db.Column(db.String(10)) 
#     team_name = db.Column(db.String(30)) 
#     game_id = db.Column(db.Integer, primary_key=True) 
#     game_date = db.Column(db.Date) 
#     matchup = db.Column(db.String(30)) 
#     wl = db.Column(db.String(10)) 
#     min = db.Column(db.Float) 
#     pts = db.Column(db.Float) 
#     fgm = db.Column(db.Float) 
#     fga = db.Column(db.Float)
#     fg_pct = db.Column(db.Float) 
#     fg3m = db.Column(db.Float) 
#     fg3a = db.Column(db.Float)
#     fg3_pct = db.Column(db.Float)
#     ftm = db.Column(db.Float)
#     fta = db.Column(db.Float) 
#     ft_pct = db.Column(db.Float) 
#     oreb = db.Column(db.Float)
#     dreb = db.Column(db.Float) 
#     reb = db.Column(db.Float) 
#     ast = db.Column(db.Float) 
#     stl = db.Column(db.Float) 
#     blk = db.Column(db.Float)
#     tov = db.Column(db.Float)
#     pf = db.Column(db.Float)
#     plus_minus = db.Column(db.Float)
#     is_win = db.Column(db.Float)
#     is_loss = db.Column(db.Float)
#     home_away = db.Column(db.String(10))
#     opponent = db.Column(db.String(10))


# class season_por(db.Model):
#     season_id = db.Column(db.Float)
#     team_id= db.Column(db.Float)
#     team_abbreviation = db.Column(db.String(10)) 
#     team_name = db.Column(db.String(30)) 
#     game_id = db.Column(db.Integer, primary_key=True) 
#     game_date = db.Column(db.Date) 
#     matchup = db.Column(db.String(30)) 
#     wl = db.Column(db.String(10)) 
#     min = db.Column(db.Float) 
#     pts = db.Column(db.Float) 
#     fgm = db.Column(db.Float) 
#     fga = db.Column(db.Float)
#     fg_pct = db.Column(db.Float) 
#     fg3m = db.Column(db.Float) 
#     fg3a = db.Column(db.Float)
#     fg3_pct = db.Column(db.Float)
#     ftm = db.Column(db.Float)
#     fta = db.Column(db.Float) 
#     ft_pct = db.Column(db.Float) 
#     oreb = db.Column(db.Float)
#     dreb = db.Column(db.Float) 
#     reb = db.Column(db.Float) 
#     ast = db.Column(db.Float) 
#     stl = db.Column(db.Float) 
#     blk = db.Column(db.Float)
#     tov = db.Column(db.Float)
#     pf = db.Column(db.Float)
#     plus_minus = db.Column(db.Float)
#     is_win = db.Column(db.Float)
#     is_loss = db.Column(db.Float)
#     home_away = db.Column(db.String(10))
#     opponent = db.Column(db.String(10))


# class season_san_sas(db.Model):
#     season_id = db.Column(db.Float)
#     team_id= db.Column(db.Float)
#     team_abbreviation = db.Column(db.String(10)) 
#     team_name = db.Column(db.String(30)) 
#     game_id = db.Column(db.Integer, primary_key=True) 
#     game_date = db.Column(db.Date) 
#     matchup = db.Column(db.String(30)) 
#     wl = db.Column(db.String(10)) 
#     min = db.Column(db.Float) 
#     pts = db.Column(db.Float) 
#     fgm = db.Column(db.Float) 
#     fga = db.Column(db.Float)
#     fg_pct = db.Column(db.Float) 
#     fg3m = db.Column(db.Float) 
#     fg3a = db.Column(db.Float)
#     fg3_pct = db.Column(db.Float)
#     ftm = db.Column(db.Float)
#     fta = db.Column(db.Float) 
#     ft_pct = db.Column(db.Float) 
#     oreb = db.Column(db.Float)
#     dreb = db.Column(db.Float) 
#     reb = db.Column(db.Float) 
#     ast = db.Column(db.Float) 
#     stl = db.Column(db.Float) 
#     blk = db.Column(db.Float)
#     tov = db.Column(db.Float)
#     pf = db.Column(db.Float)
#     plus_minus = db.Column(db.Float)
#     is_win = db.Column(db.Float)
#     is_loss = db.Column(db.Float)
#     home_away = db.Column(db.String(10))
#     opponent = db.Column(db.String(10))


# class season_tor(db.Model):
#     season_id = db.Column(db.Float)
#     team_id= db.Column(db.Float)
#     team_abbreviation = db.Column(db.String(10)) 
#     team_name = db.Column(db.String(30)) 
#     game_id = db.Column(db.Integer, primary_key=True) 
#     game_date = db.Column(db.Date) 
#     matchup = db.Column(db.String(30)) 
#     wl = db.Column(db.String(10)) 
#     min = db.Column(db.Float) 
#     pts = db.Column(db.Float) 
#     fgm = db.Column(db.Float) 
#     fga = db.Column(db.Float)
#     fg_pct = db.Column(db.Float) 
#     fg3m = db.Column(db.Float) 
#     fg3a = db.Column(db.Float)
#     fg3_pct = db.Column(db.Float)
#     ftm = db.Column(db.Float)
#     fta = db.Column(db.Float) 
#     ft_pct = db.Column(db.Float) 
#     oreb = db.Column(db.Float)
#     dreb = db.Column(db.Float) 
#     reb = db.Column(db.Float) 
#     ast = db.Column(db.Float) 
#     stl = db.Column(db.Float) 
#     blk = db.Column(db.Float)
#     tov = db.Column(db.Float)
#     pf = db.Column(db.Float)
#     plus_minus = db.Column(db.Float)
#     is_win = db.Column(db.Float)
#     is_loss = db.Column(db.Float)
#     home_away = db.Column(db.String(10))
#     opponent = db.Column(db.String(10))

# class season_was(db.Model):
#     season_id = db.Column(db.Float)
#     team_id= db.Column(db.Float)
#     team_abbreviation = db.Column(db.String(10)) 
#     team_name = db.Column(db.String(30)) 
#     game_id = db.Column(db.Integer, primary_key=True) 
#     game_date = db.Column(db.Date) 
#     matchup = db.Column(db.String(30)) 
#     wl = db.Column(db.String(10)) 
#     min = db.Column(db.Float) 
#     pts = db.Column(db.Float) 
#     fgm = db.Column(db.Float) 
#     fga = db.Column(db.Float)
#     fg_pct = db.Column(db.Float) 
#     fg3m = db.Column(db.Float) 
#     fg3a = db.Column(db.Float)
#     fg3_pct = db.Column(db.Float)
#     ftm = db.Column(db.Float)
#     fta = db.Column(db.Float) 
#     ft_pct = db.Column(db.Float) 
#     oreb = db.Column(db.Float)
#     dreb = db.Column(db.Float) 
#     reb = db.Column(db.Float) 
#     ast = db.Column(db.Float) 
#     stl = db.Column(db.Float) 
#     blk = db.Column(db.Float)
#     tov = db.Column(db.Float)
#     pf = db.Column(db.Float)
#     plus_minus = db.Column(db.Float)
#     is_win = db.Column(db.Float)
#     is_loss = db.Column(db.Float)
#     home_away = db.Column(db.String(10))
#     opponent = db.Column(db.String(10))

# class season_uta_uth(db.Model):
#     season_id = db.Column(db.Float)
#     team_id= db.Column(db.Float)
#     team_abbreviation = db.Column(db.String(10)) 
#     team_name = db.Column(db.String(30)) 
#     game_id = db.Column(db.Integer, primary_key=True) 
#     game_date = db.Column(db.Date) 
#     matchup = db.Column(db.String(30)) 
#     wl = db.Column(db.String(10)) 
#     min = db.Column(db.Float) 
#     pts = db.Column(db.Float) 
#     fgm = db.Column(db.Float) 
#     fga = db.Column(db.Float)
#     fg_pct = db.Column(db.Float) 
#     fg3m = db.Column(db.Float) 
#     fg3a = db.Column(db.Float)
#     fg3_pct = db.Column(db.Float)
#     ftm = db.Column(db.Float)
#     fta = db.Column(db.Float) 
#     ft_pct = db.Column(db.Float) 
#     oreb = db.Column(db.Float)
#     dreb = db.Column(db.Float) 
#     reb = db.Column(db.Float) 
#     ast = db.Column(db.Float) 
#     stl = db.Column(db.Float) 
#     blk = db.Column(db.Float)
#     tov = db.Column(db.Float)
#     pf = db.Column(db.Float)
#     plus_minus = db.Column(db.Float)
#     is_win = db.Column(db.Float)
#     is_loss = db.Column(db.Float)
#     home_away = db.Column(db.String(10))
#     opponent = db.Column(db.String(10))



    # id = db.Column(db.Integer, primary_key=True)
    # name = db.Column(db.String(30))
    # age = db.Column(db.Integer)

    # def to_dict(self):
    #     return {
    #         column.name: getattr(self, column.name)
    #         if not isinstance(
    #             getattr(self, column.name), (datetime.datetime, datetime.date)
    #         )
    #         else getattr(self, column.name).isoformat()
    #         for column in self.__table__.columns
    #     }

db.create_all()

@app.route("/")
def main():
    return "The app is up!"

# @app.route("/add_pet", methods=["POST"])
# def add_pet():
#     try:

#         name = request.json.get("name")
#         age = int(request.json.get("age"))
#         new_pet = Pet(name=name, age=age)

#         db.session.add(new_pet)
#         db.session.commit()

#         return {"msg": "Success"}

#     except Exception as e:
#         return {"error": str(e)}

# @app.route("/update", methods=["POST"])
# def update():

#     try:
#         pet_id = int(request.args.get("id"))

#         new_age = request.json.get("age")
#         new_name = request.json.get("name")

#         pet = Pet.query.filter(Pet.id == pet_id).first()

#         if new_age:
#             pet.age = int(new_age)
#         if new_name:
#             pet.name = new_name

#         db.session.commit()

#         return {"msg": "Success"}
    
#     except Exception as e:
#         return {"error": str(e)}

# @app.route("/delete_pet")
# def delete_pet():

#     try:
#         pet_id = int(request.args.get("id"))

#         pet = Pet.query.filter(Pet.id == pet_id).first()

#         db.session.delete(pet)
#         db.session.commit()
        
#         return {"msg": "Success"}
#     except Exception as e:
#         return {"error": str(e)}


# def show(min_age=None, max_age=None, name=None):
    
#     q = Pet.query

#     if min_age:
#         q = q.filter(Pet.age >= int(min_age))

#     if max_age:
#         q = q.filter(Pet.age <= int(max_age))

#     if name:
#         q = q.filer(Pet.name == name)

#     pets = q.all()
#     return jsonify([pet.to_dict() for pet in pets])


# @app.route("/search")
# def query_by_age():

#     min_age = request.args.get("min_age")
#     max_age = request.args.get("max_age")
#     name = request.args.get("name")

#     q = Pet.query

#     if min_age:
#         q = q.filter(Pet.age >= int(min_age))

#     if max_age:
#         q = q.filter(Pet.age <= int(max_age))

#     if name:
#         q = q.filter(Pet.name == name)

#     pets = q.all()
#     return jsonify([pet.to_dict() for pet in pets])


if __name__ == "__main__":
    app.run(debug=True)

